name: Generate Version Info

on:
  workflow_dispatch:
  
jobs:
  generate_versioninfo:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Generate System32 VersionInfo
      run: |
        $ver = [System.Environment]::OSVersion.Version -join '.'
        $sys32 = "${ver}-versioninfo-system32.json"
        $sys32recurse = "${ver}-versioninfo-system32-recurse.json"
        $allrecurse = "${ver}-versioninfo-system32-winprogiles-recurse.json"
        $allpaths_to_scan = "C:\Program*\Mi*","C:\Program*\Win*", "C:\Windows\System32\"
        $bin_types = "*.exe","*.dll","*.sys","*.winmd","*.cpl","*.ax","*.node","*.ocx","*.efi","*.acm","*.scr","*.tsp","*.drv"
        Get-ChildItem "C:\Windows\system32\*" -Include $bin_types -ErrorAction SilentlyContinue | select  Name,VersionInfo | ConvertTo-Json -depth 100 | Out-File $sys32
        Get-ChildItem "C:\Windows\system32\*" -Include $bin_types -Recurse -ErrorAction SilentlyContinue | select  Name,VersionInfo | ConvertTo-Json -depth 100 | Out-File $sys32recurse
        Get-ChildItem $allpaths_to_scan -Include $bin_types -Recurse -ErrorAction SilentlyContinue | select  Name,VersionInfo | ConvertTo-Json -depth 100 | Out-File $sys32recurse
        

    # Upload Artifacts 
    - name: Upload VersionInfo Json
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: version-info-json
        path: ./*.json
